Palo alto
Let-s-help-each-other/COVID19-resources pull request #6
Opened 2020-03-21 14:20 UTC by kgiori

added resource links for Palo Alto

2020-03-21 18:52 UTC, nancyhang requested changes
Thanks! Kathy, can you please put this under San Mateo County before approving to be merged to master?

2020-03-21 18:52 UTC, nancyhang commented
Actually, I mean Santa Clara county section, not San Mateo county.

2020-03-21 22:08 UTC, ssami commented on README.md
> +Go [here](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Immunization/ncov2019.aspx) for the State of California Department of Public Health.
Things like this website, CDC and links that aren't specific to Palo Alto can actually be put up at the top of the readme. Thanks for adding those links!

2020-03-22 22:39 UTC, kgiori commented
the added palo alto section was listed under Santa Clara county, so I'll merge it and see what happens. :)

2020-03-22 22:40 UTC, merged